### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by ey3ball** [scaleway/image-app-gitlab#3]
Simple performance test :
1) git clone --mirror https://github.com/torvalds/linux
2) git remote add scaleway [instance url + new project path]
3) git push --mirror scaleway
4) go the web interface and attempt to browse the project

Results :
(3) takes approximately 30-35 minutes average upload speed is 3.5Mo/s (limited by the instance, I'm pushing from a GBit link), most of the time is taken by git index-pack after the upload.

(4) Attempting to browse the project on gitlab results in :
502 GitLab is taking too much time to respond

**Comment by edouardb** [comment]
I tried it on a fresh server, same result. If you have any idea to increase performances.

However, I can browse the project without any issue. http://212.47.244.104/root/asdasda

Are you using the latest version of gitlab instantapp?

**Comment by edouardb** [comment]
Can you try to add swap? `fallocate -l 2G /swapfile ;  chmod 600 /swapfile ; mkswap /swapfile ; swapon /swapfile` It solved the problem on my instance

**Comment by ey3ball** [comment]
I think that sadly performance is mostly CPU-bound here.

Good to know the crash can be solved.

**Comment by edouardb** [comment]
Agree!
I will add a swap file and re-publish app.

Many thanks for help
